version: '3.7'

# the web client <-> the web server <-> the socket <-> uwsgi <-> Django

services:
    nginx:
        container_name: "kpi-info-nginx"
        build: ./nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./kpi_info:/usr/share/nginx/html
        working_dir: /usr/share/nginx/html
    python:
        container_name: "kpi-info-python"
        build: ./python
        volumes:
            - ./kpi_info:/usr/share/nginx/html
        working_dir: /usr/share/nginx/html
    mariadb:
        container_name: "kpi-info-mariadb"
        build: ./mariadb
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: 'kpi-info'
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'idktestpasswd'
            MYSQL_ROOT_PASSWORD: 'idktestpasswd'
    certbot:
        image: certbot/certbot

