# Generated by Django 2.2.4 on 2019-09-16 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.BigIntegerField(unique=True)),
                ('server_index', models.IntegerField()),
                ('player_id', models.BigIntegerField()),
                ('player_name', models.CharField(max_length=50)),
                ('pay_money', models.FloatField()),
                ('order_time', models.DateTimeField()),
            ],
        ),
    ]
