# Generated by Django 2.2.3 on 2019-07-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='transid',
            field=models.CharField(default='transidtest', max_length=100),
            preserve_default=False,
        ),
    ]
