# Generated by Django 2.2.3 on 2019-07-30 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_revenue_transid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenue',
            name='transid',
        ),
    ]
