# Generated by Django 2.2.3 on 2019-07-30 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_revenue_transid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Revenue',
        ),
    ]
