# Generated by Django 2.2.3 on 2019-07-30 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20190730_0913'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Revenue',
        ),
    ]
