# Generated by Django 2.2.3 on 2019-07-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0007_delete_revenue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
